keys:
  - &admin age1rhgd2a2qy9gh6zeq7a805qfddksejujdg96anzm373dhysxrtqlqdd8a0h
  - &larsg age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy

creation_rules:
  # Rules for admin secrets
  - path_regex: secrets/*
    key_groups:
      - age:
        - *admin
        - *larsg
